/**
 * Stable application error codes for user-facing failures.
 * Used by API services, Hono routes, and client i18n mappers.
 */
export const APP_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  SUPER_ADMIN_REQUIRED: "SUPER_ADMIN_REQUIRED",
  AUTH_UNAVAILABLE: "AUTH_UNAVAILABLE",

  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_INPUT: "INVALID_INPUT",
  OTP_SEND_RATE_LIMITED: "OTP_SEND_RATE_LIMITED",
  OTP_VERIFY_FAILED: "OTP_VERIFY_FAILED",

  REGISTRATION_DISABLED: "REGISTRATION_DISABLED",
  INVITATION_EMAIL_MISMATCH: "INVITATION_EMAIL_MISMATCH",
  NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
  INVALID_INVITATION: "INVALID_INVITATION",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_EXISTS: "INVITATION_ALREADY_EXISTS",
  INVITATION_INVALID_STATUS: "INVITATION_INVALID_STATUS",
  INVITATION_EMAIL_FAILED: "INVITATION_EMAIL_FAILED",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CANNOT_BAN_SELF: "CANNOT_BAN_SELF",
  CANNOT_BAN_SUPER_ADMIN: "CANNOT_BAN_SUPER_ADMIN",
  USER_NOT_BANNED: "USER_NOT_BANNED",

  S3_NOT_CONFIGURED: "S3_NOT_CONFIGURED",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_REQUIRED: "FILE_REQUIRED",
  INVALID_DIRECTORY: "INVALID_DIRECTORY",
  DIRECTORY_TOO_LONG: "DIRECTORY_TOO_LONG",
  FILE_EMPTY: "FILE_EMPTY",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  STORAGE_KEY_REQUIRED: "STORAGE_KEY_REQUIRED",
  STORAGE_ACCESS_DENIED: "STORAGE_ACCESS_DENIED",

  MCP_SERVER_NOT_FOUND: "MCP_SERVER_NOT_FOUND",
  MCP_TOOL_NOT_FOUND: "MCP_TOOL_NOT_FOUND",
  MCP_HOST_NOT_ALLOWED: "MCP_HOST_NOT_ALLOWED",
  MCP_MUTATION_NOT_ALLOWED: "MCP_MUTATION_NOT_ALLOWED",
  MCP_AGENT_TOKEN_INVALID: "MCP_AGENT_TOKEN_INVALID",
  MCP_UPSTREAM_ERROR: "MCP_UPSTREAM_ERROR",
  MCP_CURL_INVALID: "MCP_CURL_INVALID",
  MCP_TOOL_NAME_CONFLICT: "MCP_TOOL_NAME_CONFLICT",
  MCP_SERVER_SLUG_CONFLICT: "MCP_SERVER_SLUG_CONFLICT",
  MCP_TEMPLATE_UNRESOLVED: "MCP_TEMPLATE_UNRESOLVED",
  MCP_VARIABLE_NAME_CONFLICT: "MCP_VARIABLE_NAME_CONFLICT",
  MCP_PLAINTEXT_SECRET: "MCP_PLAINTEXT_SECRET",

  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type AppErrorCode =
  (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];

/** Optional structured payload forwarded on AppError / tRPC `data.details`. */
export type AppErrorDetails = {
  placeholder?: string;
};

const appErrorCodeValues = Object.values(APP_ERROR_CODES);

export function isAppErrorCode(value: unknown): value is AppErrorCode {
  return (
    typeof value === "string" &&
    (appErrorCodeValues as readonly string[]).includes(value)
  );
}

export function assertUniqueAppErrorCodes(): void {
  const seen = new Set<string>();
  for (const value of appErrorCodeValues) {
    if (seen.has(value)) {
      throw new Error(`Duplicate AppErrorCode value: ${value}`);
    }
    seen.add(value);
  }
}
