export { MCP_PLATFORM_SCOPES } from "@repo/core";
export {
  MCP_DEFAULT_PLATFORM_SCOPES,
  MCP_MAX_ACTIVE_PLATFORM_TOKENS,
  MCP_PLATFORM_HIGH_RISK_SCOPES,
  MCP_PLATFORM_HIGH_RISK_TTL_DEFAULT_DAYS,
  MCP_PLATFORM_HIGH_RISK_TTL_MAX_DAYS,
  MCP_PLATFORM_LOW_RISK_TTL_DEFAULT_DAYS,
  MCP_PLATFORM_LOW_RISK_TTL_MAX_DAYS,
  MCP_PLATFORM_PRESET_IDS,
  MCP_PLATFORM_PRESETS,
  MCP_PLATFORM_SCOPE_DEPENDENCIES,
} from "@repo/core";
export type {
  McpPlatformPreset,
  McpPlatformResourceMode,
  McpPlatformScope,
} from "@repo/core";

export const MCP_MAX_TOOLS = 50;
