/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as PrivacyRouteImport } from './../routes/privacy'
import { Route as TermsRouteImport } from './../routes/terms'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as appAdminRouteRouteImport } from './../routes/(app)/admin/route'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as authSignupRouteImport } from './../routes/(auth)/signup'
import { Route as authVerifyEmailRouteImport } from './../routes/(auth)/verify-email'
import { Route as appAdminIndexRouteImport } from './../routes/(app)/admin/index'
import { Route as appAdminAuditLogRouteImport } from './../routes/(app)/admin/audit-log'
import { Route as appAdminInvitationsRouteImport } from './../routes/(app)/admin/invitations'
import { Route as appAdminSettingsRouteImport } from './../routes/(app)/admin/settings'
import { Route as appAdminUsersRouteImport } from './../routes/(app)/admin/users'
import { Route as appServersIndexRouteImport } from './../routes/(app)/servers/index'
import { Route as appServersServerIdRouteImport } from './../routes/(app)/servers/$serverId'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const appAdminIndexRoute = appAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminAuditLogRoute = appAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminInvitationsRoute = appAdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSettingsRoute = appAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminUsersRoute = appAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appServersIndexRoute = appServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => appRouteRoute,
} as any)
const appServersServerIdRoute = appServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof appAdminRouteRouteWithChildren
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/admin/audit-log': typeof appAdminAuditLogRoute
  '/admin/invitations': typeof appAdminInvitationsRoute
  '/admin/settings': typeof appAdminSettingsRoute
  '/admin/users': typeof appAdminUsersRoute
  '/servers/$serverId': typeof appServersServerIdRoute
  '/admin/': typeof appAdminIndexRoute
  '/servers/': typeof appServersIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/admin/audit-log': typeof appAdminAuditLogRoute
  '/admin/invitations': typeof appAdminInvitationsRoute
  '/admin/settings': typeof appAdminSettingsRoute
  '/admin/users': typeof appAdminUsersRoute
  '/servers/$serverId': typeof appServersServerIdRoute
  '/admin': typeof appAdminIndexRoute
  '/servers': typeof appServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(app)/admin': typeof appAdminRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/admin/audit-log': typeof appAdminAuditLogRoute
  '/(app)/admin/invitations': typeof appAdminInvitationsRoute
  '/(app)/admin/settings': typeof appAdminSettingsRoute
  '/(app)/admin/users': typeof appAdminUsersRoute
  '/(app)/servers/$serverId': typeof appServersServerIdRoute
  '/(app)/admin/': typeof appAdminIndexRoute
  '/(app)/servers/': typeof appServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/settings'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/admin/audit-log'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/users'
    | '/servers/$serverId'
    | '/admin/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/admin/audit-log'
    | '/admin/invitations'
    | '/admin/settings'
    | '/admin/users'
    | '/servers/$serverId'
    | '/admin'
    | '/servers'
  id:
    | '__root__'
    | '/(app)'
    | '/privacy'
    | '/terms'
    | '/(app)/admin'
    | '/(app)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/(app)/'
    | '/(app)/admin/audit-log'
    | '/(app)/admin/invitations'
    | '/(app)/admin/settings'
    | '/(app)/admin/users'
    | '/(app)/servers/$serverId'
    | '/(app)/admin/'
    | '/(app)/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin': {
      id: '/(app)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/admin/': {
      id: '/(app)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof appAdminIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/admin/audit-log': {
      id: '/(app)/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof appAdminAuditLogRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/admin/invitations': {
      id: '/(app)/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof appAdminInvitationsRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/admin/settings': {
      id: '/(app)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof appAdminSettingsRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/admin/users': {
      id: '/(app)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof appAdminUsersRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/servers/': {
      id: '/(app)/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof appServersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/servers/$serverId': {
      id: '/(app)/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof appServersServerIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminAuditLogRoute: typeof appAdminAuditLogRoute
  appAdminInvitationsRoute: typeof appAdminInvitationsRoute
  appAdminSettingsRoute: typeof appAdminSettingsRoute
  appAdminUsersRoute: typeof appAdminUsersRoute
  appAdminIndexRoute: typeof appAdminIndexRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminAuditLogRoute: appAdminAuditLogRoute,
  appAdminInvitationsRoute: appAdminInvitationsRoute,
  appAdminSettingsRoute: appAdminSettingsRoute,
  appAdminUsersRoute: appAdminUsersRoute,
  appAdminIndexRoute: appAdminIndexRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appSettingsRoute: typeof appSettingsRoute
  appIndexRoute: typeof appIndexRoute
  appServersServerIdRoute: typeof appServersServerIdRoute
  appServersIndexRoute: typeof appServersIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appSettingsRoute: appSettingsRoute,
  appIndexRoute: appIndexRoute,
  appServersServerIdRoute: appServersServerIdRoute,
  appServersIndexRoute: appServersIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
